version: '3.8'

services:
  frontend:
    container_name: devmountain-frontend
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:443"  # 도메인 연결을 위한 443 외부포트(HTTPS)
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - devmountain-perf-net
    environment:
      - NODE_ENV=development

networks:
  devmountain-perf-net:
    external: true
